Hw2
SynkovAndrew/otus-spring-2024-07-synkov pull request #2
Opened 2024-08-11 15:32 UTC by SynkovAndrew

2024-08-14 20:00 UTC, VladimirMagerov requested changes

2024-08-14 20:00 UTC, VladimirMagerov commented on homework/homework-2-java-configuration-context/src/main/java/otus/spring/domain/TestResult.java
> +    public void answerQuestion(Question question, String answer) {
Это выглядит как бизнес логика, которая не должна быть в доменном классе. Предлагаю это перенести в подходящий сервис.
В добавок к этому, по текущей логике вопросы задаются с вариантом выбора ответа, а ответ предлагается не выбирать, а вводить вручную, надо это привести к единому формату - либо вопрос с вариантами и ввод номера ответа, либо вопрос без вариантов и ввод ответа в свободной форме.

2024-08-14 20:00 UTC, VladimirMagerov commented on homework/homework-2-java-configuration-context/src/test/java/otus/spring/dao/TestResultServiceUnitTest.java
> +        assertEquals(
Советую как-то переписать эти тесты, чтобы они не сравнивали такой большой многострочный текст как единое целое, лучше как-то разбить на части - как последствие, например, на моём локальном компьютере эти тесты не проходят, хотя я вижу что контент по факту идентичен (может быть разница между ОС или в каких-то системных настройках).

2024-08-15 22:39 UTC, SynkovAndrew commented on homework/homework-2-java-configuration-context/src/test/java/otus/spring/dao/TestResultServiceUnitTest.java
> +        assertEquals(
Переписал на contains по строчно

2024-08-15 22:41 UTC, SynkovAndrew commented on homework/homework-2-java-configuration-context/src/main/java/otus/spring/domain/TestResult.java
> +    public void answerQuestion(Question question, String answer) {
Бизнес логику вынес в сервис. Добавил метод в ioService, который читает число, и теперь тестирование ожидает на вход именно число для соотнесения с числом правильного или неправильно ответа.

2024-08-19 18:39 UTC, VladimirMagerov approved these changes

2024-08-20 08:06 UTC, merged