Hw3
SynkovAndrew/otus-spring-2024-07-synkov pull request #4
Opened 2024-08-20 11:58 UTC by SynkovAndrew

2024-08-22 18:30 UTC, VladimirMagerov requested changes

2024-08-22 18:30 UTC, VladimirMagerov commented on homework/homework-3-spring-boot/src/main/resources/application.yaml
> +  locale: ru_RU
1) Вместо кириллицы выводится непонятно что, вероятно, проблемы с кодировкой:
![image](https://github.com/user-attachments/assets/08e86221-2f32-4b14-b9f8-2b4b271ac565)
2) При смене локали на en_EN, программные сообщения (не вопросы) всё равно подтягиваются от RU локализации

2024-08-22 18:30 UTC, VladimirMagerov commented on homework/homework-3-spring-boot/src/test/java/otus/spring/homework3springboot/QuestionDaoIntegrationTest.java
> +        var dao = new QuestionCsvDao(() -> "test-questions.csv");
`QuestionCsvDao` теперь ждёт 2 параметра конструктора, а не один - как результат, тесты не проходят.

2024-08-22 18:30 UTC, VladimirMagerov commented on homework/homework-3-spring-boot/src/test/java/otus/spring/homework3springboot/StudentServiceUnitTest.java
> +    private final LocalizedIOService ioService = mock(LocalizedIOService.class);
Предлагаю все юнит тесты переписать в декларативном стиле, используя аннотации `@Mock`, `@InjectMocks`, `@ExtendWith(MockitoExtension.class)` - так мы избавляем себя от ответственности самим создавать и инжектить объекты-моки в тестируемый сервис.

2024-08-22 18:36 UTC, VladimirMagerov commented on homework/homework-3-spring-boot/build.gradle.kts
> +plugins {
В общепроектном `settings.gradle.kts`  третье домашнее задание ("homework-3-spring-boot") не было включено, соответственно, инструмент сборки не обработал его автоматически и не настроил нужным образом. Прошу вас быть внимательнее к подобным вещам, так как тратится лишнее время на то чтобы понять, почему система сборки не видит новый код.

2024-08-23 11:49 UTC, SynkovAndrew commented on homework/homework-3-spring-boot/build.gradle.kts
> +plugins {
поправил

2024-08-23 12:13 UTC, SynkovAndrew commented on homework/homework-3-spring-boot/src/test/java/otus/spring/homework3springboot/StudentServiceUnitTest.java
> +    private final LocalizedIOService ioService = mock(LocalizedIOService.class);
поправил

2024-08-23 12:37 UTC, SynkovAndrew commented on homework/homework-3-spring-boot/src/test/java/otus/spring/homework3springboot/QuestionDaoIntegrationTest.java
> +        var dao = new QuestionCsvDao(() -> "test-questions.csv");
поправил. немного обновил ci файлик, теперь там точно будет и билд и тесты, чтобы отлавливать такие неприятный моменты

2024-08-23 13:49 UTC, SynkovAndrew commented on homework/homework-3-spring-boot/src/main/resources/application.yaml
> +  locale: ru_RU
1. Странно, но я не смог воспроизвести такую проблему с кодировкой. Пробовал запускать и через idea и просто jar. И все рендерится нормально. Идею использовать unicode кодировку взял из заготовки. Поэтому, по идее, все должно быть нормально.

2. Скорее всего проблема была в том, что у меня не было добавлено messages_en_EN поэтому не найдя их, использовалась локаль вашей системы (скоррее всего русская), поэтому показывалось на русском языке. Я добавил, теперь все должно быть нормально.

2024-08-26 13:23 UTC, VladimirMagerov approved these changes

2024-08-26 14:15 UTC, merged